### ISSUE TITLE
Error: unhandled exception: invalid integer: WARNING: [ValueError]

### ISSUE THREAD

**Issue by Coac** [acatai/Strategy-Card-Game-AI-Competition#1]
When I run this command (from the [README](https://github.com/acatai/Strategy-Card-Game-AI-Competition/blob/master/referee-nim/README.md#run-cg-referee))
```
./Tester \
  --referee="java -jar LoCM.jar" \
  --player1="./Player --draft=Icebox --player=DFS --time=100" \
  --player2="./Player --draft=ClosetAI --player=FMC --time=150" \
  --games=16 \
  --threads=4
```
I get the following error:
```
2019-04-25 18:19:54.613 Referee: java -jar LoCM.jar
2019-04-25 18:19:54.613 Player1: ./Player --draft=Manual --player=Random --time=100
2019-04-25 18:19:54.613 Player2: ./Player --draft=Manual --player=Random --time=150
2019-04-25 18:19:54.613 Games:   16
2019-04-25 18:19:54.613 Replays: false
2019-04-25 18:19:54.613 Threads: 4
Error: unhandled exception: invalid integer: WARNING: [ValueError]
```

**Comment by acatai** [comment]
Is it still an issue? It is working correctly for me - with respect to making the command a true one-liner.
![image](https://user-images.githubusercontent.com/1181695/56846879-d3f64b80-68d4-11e9-9761-6b5dc521dfb1.png)

**Comment by Coac** [comment]
Yes still an issue, does not work for one liner too.
![image](https://user-images.githubusercontent.com/7363034/56847272-6698e980-68d9-11e9-92ad-27fb3c2f30e6.png)

**Comment by acatai** [comment]
I tried also on linux (clean repo clone), and it is working without such an issue.

Please make sure you have the latest version of nim - sometimes the one which is available in the system repository is heavily outdated.  I have no other ideas about the origin of this error for now :(.

**Comment by Coac** [comment]
So strange...
My nim version is the latest one (0.19.4)
```
nim --version
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```
And java version
```
java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharin
```
It works when I use directly the java referee
```
java -jar LoCM.jar -p1 "./Player --draft=Icebox --player=DFS --time=100" -p2 "./Player --draft=ClosetAI --player=FMC --time=150"
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/coac/Projects/competitions/Strategy-Card-Game-AI-Competition/referee-nim/LoCM.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
1
0
draftChoicesSeed=-9208927334695705295
shufflePlayer0Seed=-8026433766257023869
seed=-1939558166782714147
shufflePlayer1Seed=3219320295988921175
```
Is it possible that you try to read the first line of output, but there are some warnings lines?

**Comment by radekmie** [comment]
> Is it possible that you try to read the first line of output, but there are some warnings lines?

That's exactly what I thought after reading your referee output! I've used 8, 9 and 10 (or at least I'm pretty sure I did). I'm pretty sure there's a flag to suppress these warnings.

**Comment by Coac** [comment]
Okay, did not find a way to suppress all the warnings, but I edited directly the Tester.nim code for my case.
Thanks
