### ISSUE TITLE
LoCM v1.5 constructed phase cards

### ISSUE THREAD

**Issue by godmoves** [acatai/Strategy-Card-Game-AI-Competition#12]
Hi,
Are all 120 cards randomly generated for each game or selected from the [predefined 160 cards pool](https://jakubkowalski.tech/Projects/LOCM/cardlist.html)?

Thanks!

**Comment by acatai** [comment]
Hello
In v1.5 all 120 cards are generated for each game using this code: https://github.com/acatai/Strategy-Card-Game-AI-Competition/tree/master/referee1.5-java/src/main/java/com/codingame/game/engine/cardgenerator

Best,
JK.

**Comment by godmoves** [comment]
If I need to run LoCM v1.5 locally, do I need to compile it myself, or I can download it from somewhere?
