### ISSUE TITLE
LoCM v1.5 additional card draw for HP loss

### ISSUE THREAD

**Issue by godmoves** [acatai/Strategy-Card-Game-AI-Competition#13]
The v1.5 rule says:
```
Player draws an additional card for every 5 HP lost due to opponent dealing damage to player in last round.
```
and the code implements this rule by recording the HP lost in the last turn:
https://github.com/acatai/Strategy-Card-Game-AI-Competition/blob/092d99f38a62dec4d8f68dce74d6bf1c0eb560b5/referee1.5-java/src/main/java/com/codingame/game/engine/GameState.java#L178-L179
but it seems the value of `player.healthLostThisTurn` is negative, so it will make a player can't draw a card in the next turn when the player received more than 5 HP loss:
https://github.com/acatai/Strategy-Card-Game-AI-Competition/blob/092d99f38a62dec4d8f68dce74d6bf1c0eb560b5/referee1.5-java/src/main/java/com/codingame/game/engine/Gamer.java#L70-L75

**Comment by acatai** [comment]
Damn misclick.
Sorry - just wanted to say that we're working on it and thank you very much for pointing this out.
Soon we will release a new version with a few fixes and improvements.

**Comment by godmoves** [comment]
Thanks for your reply, looking forward to fixes and improvements!
