### ISSUE TITLE
Support human play

### ISSUE THREAD

**Issue by ronaldosvieira** [acatai/Strategy-Card-Game-AI-Competition#4]
Hi! 

As a card game enthusiast and AI researcher, I'd like to play LOCM as human vs human or human vs bot. I've been trying to figure out how to allow human play but haven't reached a solution yet. Simply allowing someone to input the action strings would be enough.

My current tentative is having (i) a server process that reads keyboard inputs and puts them into a shared queue; and (ii) a player process that prints the next queue element (or hangs until there's any). I hoped to see the game state via the browser visualization and act via the server process.

I did remove the time limits, but my custom java referee still gives timeout error to the player process. Do you have any insights of better approaches or why timeout error persists?

**Comment by radekmie** [comment]
Hi @ronaldosvieira!

That makes two of us. It'd be really hard to incorporate it within the CodinGame infrastructure, as the rendering engine expects to get the full replay at once (it allows things like going backwards).

On the other hand, both _engines_ (not referees) don't have such restrictions. I don't know how we could reuse the current implementation of UI to make human play possible, but I'll definitely think about it.

A very simple CLI interface can be made using a basic CLI Nim player. The only currently missing part would be the user input -> action parser.

**Comment by ronaldosvieira** [comment]
I see. Thanks!

I'll let you know if I have any progress on this.
