### ISSUE TITLE
Python and gym style example for interacting with the game binary?

### ISSUE THREAD

**Issue by ghost** [acatai/Strategy-Card-Game-AI-Competition#6]
Hi, thanks for the nice card game platform! 

Wondering if you could provide some examples for interacting with the game binary via Python (probably in `gym` style or `OpenSpiel` style), and examples for how to do that in multi-threading/multi-processing (so as to enable parallel RL)?

I did notice the online example: 
https://www.codingame.com/contribute/view/162759566f5a132f64b4de78ed637a2f309a
but got confused with the `input()` stuff (seemed that it is called from Java, and the game state is passed through stdin?);  had no idea what the calling context is and how to encapsulate the code as an gym environment. Or could you provide some guidances for doing this? I believe this would help the users (who are unfamiliar with Java/nim but are familiar with Python) focus more on machine learning alogorithm developement.

**Comment by radekmie** [comment]
Hi @wanhesong and thanks for your interest!

1. The CodinGame platform, as well as the competition, operates using standard input/output streams. It means that you agent has to read the input from `stdin` and provide the answer through `stdout` (you can use `stderr` for debugging purposes).
    * Of course this looks differently in different languages, but in Python, it's going to be `input()` and `print()` respectively.
    * The precise definition of the rules is available on the lefthand side in the CodinGame platform. Details for this years' edition will be published soon; the previous version is available [here](https://legendsofcodeandmagic.com/rules.html).
2. There are OpenAI Gym environments for LoCM made by one of the past contestants: [ronaldosvieira/gym-locm](https://github.com/ronaldosvieira/gym-locm). I haven't used it personally and I cannot guarantee any support towards it.
    * The agent itself is also public: [ronaldosvieira/reinforced-greediness](https://github.com/ronaldosvieira/reinforced-greediness).
3. I don't know what exactly you'd like to parallelize, but the Nim runner has an option to run multiple matches in parallel ([docs](https://github.com/acatai/Strategy-Card-Game-AI-Competition/tree/master/referee-nim#run-cg-referee)).

Hope that helps!

**Comment by ronaldosvieira** [comment]
Hi @wanhesong! :)

As pointed out by @radekmie (thanks!), [ronaldosvieira/gym-locm](https://github.com/ronaldosvieira/gym-locm) currently includes OpenAI Gym envs for the draft and battle phases in LoCM 1.2. As soon as [LoCM 1.5](https://legendsofcodeandmagic.com/COG22/) become available, I plan to add separate Gym envs for its constructed deck-building and battle phases too.

Feel free to reach out!

**Comment by ghost** [comment]
Thanks @radekmie, the explanations really help!

**Comment by ghost** [comment]
Hi @ronaldosvieira, it's awesome! It's exactly what I want, thanks for sharing the code!
