### ISSUE TITLE
Creatures on board lose healthChange, oppHealthChange and cardDraw attributes after participating in attack or use actions

### ISSUE THREAD

**Issue by ronaldosvieira** [acatai/Strategy-Card-Game-AI-Competition#7]
Hi!

Disclaimer: this is going to have way too much text for what it's really worth 😂

I am currently working towards ensuring that [gym-locm](https://github.com/ronaldosvieira/gym-locm)'s engine is 100% consistent with referee-java in the sense that, if an identical match (including the deck shuffling) is played on both gym-locm's engine and referee-java by the same deterministic agents, then all (state -> actions -> next_state) tuples in that match should also be identical on both engines.

With that said, I noticed that, on referee-java, after a summoned creature participates in an ATTACK or USE action, its healthChange, oppHealthChange, or cardDraw attributes are set to zero (in case they weren't already). It's not a very important issue since I don't think any agents really care about those "summon-time abilities" *after* the creature have been summoned, but I'd like to ask if this behavior is intentional or is a very small bug, so I can fix accordingly on gym-locm's engine.

Here's an example:

(Turn X)
```
27 4 21 25 1
31 4 22 25 1
4 2
99 ATTACK 1 2
13 SUMMON 15 0 # creature 15 is summoned
9
113 4 0 0 6 2 4 ---G-- 4 0 0 -1 
106 8 0 0 5 5 5 ---G-- 0 0 0 -1 
77 12 0 0 7 7 7 B----- 0 0 0 -1 
94 14 0 0 2 1 4 ---G-- 0 0 0 -1 
13 16 0 0 4 5 3 ------ 1 -1 0 -1 
81 18 0 0 9 6 6 BC---- 0 0 0 -1 
99 2 1 0 3 2 3 ---G-- 0 0 0 0 
99 1 -1 0 3 2 3 ---G-- 0 0 0 0 
13 15 -1 0 4 5 3 ------ 1 -1 0 0 # creature 15 with "1 -1 0"
```

(Turn X+1, same player)
```
26 5 20 25 1
30 5 21 25 1
4 3
13 ATTACK 15 2 # creature 15 attacks
99 ATTACK 1 -1
106 SUMMON 7 0
10
113 4 0 0 6 2 4 ---G-- 4 0 0 -1 
106 8 0 0 5 5 5 ---G-- 0 0 0 -1 
77 12 0 0 7 7 7 B----- 0 0 0 -1 
94 14 0 0 2 1 4 ---G-- 0 0 0 -1 
81 18 0 0 9 6 6 BC---- 0 0 0 -1 
79 20 0 0 8 8 8 B----- 0 0 0 -1 
13 16 1 0 4 5 3 ------ 1 -1 0 0 
99 1 -1 0 3 2 1 ---G-- 0 0 0 0 
13 15 -1 0 4 5 1 ------ 0 0 0 0 # creature 15 now with "0 0 0"
106 7 -1 0 5 5 5 ---G-- 0 0 0 0
```

In case it's not intentional, what I think it's happening code-wise is very simple:
The CreatureOnBoard class on referee-java have these constructors:
1. `public CreatureOnBoard (Card card, int lane)`, used on SUMMON.
2. `public CreatureOnBoard (CreatureOnBoard creature)`, used on ATTACK or USE.

While constructor 1 carries on the "summon-time abilities" from the Card to the CreatureOnBoard instance, constructor 2 doesn't carry them from the old CreatureOnBoard instance to the new one, and since the default value for ints in Java is 0, they remain 0.

**Comment by acatai** [comment]
Nice catch - although, as you said, it does not have any actual impact.
As far as I remember, it was done for simplicity and efficiency (possibly even to not mislead players with 'unnecessary' values).
Our other implementations (Nim, Rust) do not work this way.

**Comment by ronaldosvieira** [comment]
Thanks!
